---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: centos-7.2
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  #- name: centos
    #run_list:
      #- recipe[ohmyzsh::default]
    #verifier:
      #inspec_tests:
        #- test/smoke/centos
    #attributes:

  - name: ubuntu
    run_list:
      - recipe[ohmyzsh::default]
    verifier:
      inspec_tests:
        - test/smoke/ubuntu
    attributes:
